language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

python:
    - "2.7"
    - "3.4"
    - "3.5"

services:
  - postgresql

addons:
  postgresql: "9.4"

install:
  - pip install psycopg2
  - pip install django

before_script:
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - cd travis_test_project
  - python manage.py migrate
  - python manage.py loadmunicipios

script:
  - python manage.py checkallmunicipios
